project:
  type: website
  output-dir: docs

website:
  title: webdesign4shinydevs
  site-url: ""
  repo-url: https://github.com/posit-conf-2023/shiny-r-ui
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: ğŸ  Home
      - href: schedule.qmd
        text: ğŸ• Schedule
      - href: about.qmd
        text: ğŸ‘©â€ğŸ« ğŸ§‘â€ğŸ« About us
    right:
      - icon: github
        menu:
          - text: Code
            url: https://github.com/posit-conf-2023/shiny-r-ui
          - text: Issues
            url: https://github.com/posit-conf-2023/shiny-r-ui/issues

  sidebar:
    - title: "Slides"
      style: "docked"
      search: true
      contents:
        - ./0-welcome.qmd
        - ./1-introduction.qmd
        - ./2-best-practices.qmd
  page-navigation: true

  #page-footer: 
  #  left: "Copyright 2023, Norah Jones" 

format:
  html:
    css: ./assets/css/styles.css
    toc: true

editor: visual

